# Generated by Django 2.1.3 on 2019-07-25 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamproject', '0004_auto_20190725_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(through='teamproject.Invite', to=settings.AUTH_USER_MODEL),
        ),
    ]
