# Generated by Django 2.2.3 on 2019-07-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamproject', '0005_auto_20190725_2351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AddField(
            model_name='team',
            name='refFile',
            field=models.FileField(default=0, null=True, upload_to='refFile/'),
        ),
    ]
