# Generated by Django 2.2.3 on 2019-07-23 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_auto_20190723_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userName',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.date(2019, 7, 23)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userId',
            field=models.CharField(default='', max_length=50),
        ),
    ]
