# Generated by Django 2.1.3 on 2019-07-24 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_auto_20190724_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='userId',
        ),
    ]
