# Generated by Django 2.2.1 on 2019-07-31 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0010_auto_20190730_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.date(2019, 7, 31)),
        ),
    ]
